### ISSUE TITLE
Why is EncryptingKeypair.privkey bytes by default, but with serialization methods?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#151]
`keypairs.EncryptingKeypair` generates a private key, but then serializes it before saving it by default.  

Since we need the `Element` version for decryption, doesn't it make sense to store that?

@tux wrote serialization methods for it, which further makes me think he meant to store the `Element`.  However, those methods aren't tested, so I can't be sure.

**Comment by michwill** [comment]
Yeah, good question. We often use derived keys which are making bytes (output of keccak hash). So we need to chose which is the convenient format to keep the private keys in when in variables

**Comment by tuxxy** [comment]
The issue with storing the `Element` is that you also convert this to bytes to serialize it. Actually serializing or de-serializing the `Element` object is something handled in Charm/OpenSSL.

As for the serialization functions -- Since we don't have a standard way of serializing them, we had to handle that ourselves. It adds the metabytes to it so we can reserialize it properly as that specific key (private or public, signing or encrypting).

Cryptography.io has exceptional methods for storing these in portable and standard forms, which is what I'm aiming to use next. This will allow us to cut back on a lot of this code and handle serialization there. I don't think we will have to worry about any of the metabyte specific stuff anymore there, either.

**Comment by tuxxy** [comment]
Won't fix. Solved in `PyUmbral`.
