### ISSUE TITLE
Add serialization to umbral

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#50]
I've [implemented](https://github.com/nucypher/nucypher-pre-python/tree/umbral) umbral in nucypher-pre-python.

What needs to be done is serialization to/from bytes. I think, it makes sense to do it in a form of a decorator (so that the algorithms stay readable):
```python
class PRE(object):
    @serializer
    def priv2pub(self, priv_key: ec.ec_element) -> ec.ec_element:
        ...
```
which converts bytes to the type in the typestring when bytes are passed (could be an ec element or a named tuple). Function [get_type_hints](https://docs.python.org/3/library/typing.html#typing.get_type_hints) can help here.

**Comment by tuxxy** [comment]
I'm gonna close this issue because we settled on a solution on this for now.

To recap, we will handle all serialization in the `KeyRing` class. We may iterate on top of this in the future to allow more customization in this, but we will implement a basic way for users to use the Cryptographic API with Umbral for now.
