### ISSUE TITLE
Use umbral for public key encryption

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#51]
With BBS98, a symmetric key was generated randomly. In ECIES it's a little different: you get a symmetric key (which will be a DH shared secred) generated.

Also umbral shares between two private keys, need to do the same trick as I did with bbs98 converting it to private->public sharing (or, better, make this private>public conversion universal for any algorithm).

**Comment by cygnusv** [comment]
Note that ECIES-KEM requires to encrypt and authenticate the data using the derived key (or keys). In our case, we can directly use an authenticated encryption scheme. Right now the code seems to use PyNaCL Secret box for encryption, which it's good since it's authenticated encryption, but maybe it should get clearly reflected somewhere in the code, just in case at some point we/someone changes it and forgot this detail. Perhaps some kind of generic interface on top of the symmetric encryption that specifies that it has to be authenticated, or whatever you think it's sufficient.

**Comment by tuxxy** [comment]
Completed in #55.
